# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TecrsHeightExtractor
                                 A QGIS plugin
 Extracts building heights from VHR satellite imagery shadows using vertex-comb ray casting.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-24
        copyright            : (C) 2026 by TECRSLab
        email                : admin@tecrslab.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'TECRSLab'
__date__ = '2026-07-24'
__copyright__ = '(C) 2026 by TECRSLab'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TecrsHeightExtractor class from file TecrsHeightExtractor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tecrs_height_extractor import TecrsHeightExtractorPlugin
    return TecrsHeightExtractorPlugin()
